# pylint: disable=invalid-name,redefined-builtin,line-too-long
# pylint: disable=missing-class-docstring,missing-function-docstring
"""Auto generated. Do not touch."""
from mnm._lib import _APIS
# Defined in ./src/op/regs/regs.cc
_allgather = _APIS.get("mnm.op.imp._allgather", None)
# Defined in ./src/op/regs/regs.cc
_allreduce = _APIS.get("mnm.op.imp._allreduce", None)
# Defined in ./src/op/regs/regs.cc
_contrib_dropout = _APIS.get("mnm.op.imp._contrib_dropout", None)
# Defined in ./src/op/regs/regs.cc
_contrib_dropout_dx = _APIS.get("mnm.op.imp._contrib_dropout_dx", None)
# Defined in ./src/op/regs/regs.cc
_reduce_scatter = _APIS.get("mnm.op.imp._reduce_scatter", None)
# Defined in ./src/op/regs/regs.cc
abs = _APIS.get("mnm.op.imp.abs", None)
# Defined in ./src/op/regs/regs.cc
adaptive_avg_pool2d = _APIS.get("mnm.op.imp.adaptive_avg_pool2d", None)
# Defined in ./src/op/regs/regs.cc
adaptive_avg_pool2d_dx = _APIS.get("mnm.op.imp.adaptive_avg_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
adaptive_max_pool2d = _APIS.get("mnm.op.imp.adaptive_max_pool2d", None)
# Defined in ./src/op/regs/regs.cc
adaptive_max_pool2d_dx = _APIS.get("mnm.op.imp.adaptive_max_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
add = _APIS.get("mnm.op.imp.add", None)
# Defined in ./src/op/regs/regs.cc
adv_index = _APIS.get("mnm.op.imp.adv_index", None)
# Defined in ./src/op/regs/regs.cc
adv_index_dx = _APIS.get("mnm.op.imp.adv_index_dx", None)
# Defined in ./src/op/regs/regs.cc
all = _APIS.get("mnm.op.imp.all", None)
# Defined in ./src/op/regs/regs.cc
any = _APIS.get("mnm.op.imp.any", None)
# Defined in ./src/op/regs/regs.cc
arange = _APIS.get("mnm.op.imp.arange", None)
# Defined in ./src/op/regs/regs.cc
argmax = _APIS.get("mnm.op.imp.argmax", None)
# Defined in ./src/op/regs/regs.cc
argmin = _APIS.get("mnm.op.imp.argmin", None)
# Defined in ./src/op/regs/regs.cc
argsort = _APIS.get("mnm.op.imp.argsort", None)
# Defined in ./src/op/regs/regs.cc
argwhere = _APIS.get("mnm.op.imp.argwhere", None)
# Defined in ./src/op/regs/regs.cc
atan = _APIS.get("mnm.op.imp.atan", None)
# Defined in ./src/op/regs/regs.cc
avg_pool2d = _APIS.get("mnm.op.imp.avg_pool2d", None)
# Defined in ./src/op/regs/regs.cc
avg_pool2d_dx = _APIS.get("mnm.op.imp.avg_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
batch_flatten = _APIS.get("mnm.op.imp.batch_flatten", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul = _APIS.get("mnm.op.imp.batch_matmul", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul_nt = _APIS.get("mnm.op.imp.batch_matmul_nt", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul_tn = _APIS.get("mnm.op.imp.batch_matmul_tn", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul_tt = _APIS.get("mnm.op.imp.batch_matmul_tt", None)
# Defined in ./src/op/regs/regs.cc
batch_norm_infer = _APIS.get("mnm.op.imp.batch_norm_infer", None)
# Defined in ./src/op/regs/regs.cc
batch_norm_train = _APIS.get("mnm.op.imp.batch_norm_train", None)
# Defined in ./src/op/regs/regs.cc
batch_norm_train_dxwb = _APIS.get("mnm.op.imp.batch_norm_train_dxwb", None)
# Defined in ./src/op/regs/regs.cc
bias_add = _APIS.get("mnm.op.imp.bias_add", None)
# Defined in ./src/op/regs/regs.cc
broadcast_to = _APIS.get("mnm.op.imp.broadcast_to", None)
# Defined in ./src/op/regs/regs.cc
broadcast_to_like = _APIS.get("mnm.op.imp.broadcast_to_like", None)
# Defined in ./src/op/regs/regs.cc
cast = _APIS.get("mnm.op.imp.cast", None)
# Defined in ./src/op/regs/regs.cc
cast_like = _APIS.get("mnm.op.imp.cast_like", None)
# Defined in ./src/op/regs/regs.cc
ceil = _APIS.get("mnm.op.imp.ceil", None)
# Defined in ./src/op/regs/regs.cc
clip = _APIS.get("mnm.op.imp.clip", None)
# Defined in ./src/op/regs/regs.cc
clip_dx = _APIS.get("mnm.op.imp.clip_dx", None)
# Defined in ./src/op/regs/regs.cc
collapse_sum_like = _APIS.get("mnm.op.imp.collapse_sum_like", None)
# Defined in ./src/op/regs/regs.cc
compiler_begin = _APIS.get("mnm.op.imp.compiler_begin", None)
# Defined in ./src/op/regs/regs.cc
compiler_end = _APIS.get("mnm.op.imp.compiler_end", None)
# Defined in ./src/op/regs/regs.cc
concatenate = _APIS.get("mnm.op.imp.concatenate", None)
# Defined in ./src/op/regs/regs.cc
concatenate_dx = _APIS.get("mnm.op.imp.concatenate_dx", None)
# Defined in ./src/op/regs/regs.cc
conv2d = _APIS.get("mnm.op.imp.conv2d", None)
# Defined in ./src/op/regs/regs.cc
conv2d_dw = _APIS.get("mnm.op.imp.conv2d_dw", None)
# Defined in ./src/op/regs/regs.cc
conv2d_dx = _APIS.get("mnm.op.imp.conv2d_dx", None)
# Defined in ./src/op/regs/regs.cc
conv2d_transpose = _APIS.get("mnm.op.imp.conv2d_transpose", None)
# Defined in ./src/op/regs/regs.cc
conv2d_transpose_dw = _APIS.get("mnm.op.imp.conv2d_transpose_dw", None)
# Defined in ./src/op/regs/regs.cc
conv2d_transpose_dx = _APIS.get("mnm.op.imp.conv2d_transpose_dx", None)
# Defined in ./src/op/regs/regs.cc
copy = _APIS.get("mnm.op.imp.copy", None)
# Defined in ./src/op/regs/regs.cc
cos = _APIS.get("mnm.op.imp.cos", None)
# Defined in ./src/op/regs/regs.cc
cross_entropy = _APIS.get("mnm.op.imp.cross_entropy", None)
# Defined in ./src/op/regs/regs.cc
cross_entropy_dpred = _APIS.get("mnm.op.imp.cross_entropy_dpred", None)
# Defined in ./src/op/regs/regs.cc
cross_entropy_dtrue = _APIS.get("mnm.op.imp.cross_entropy_dtrue", None)
# Defined in ./src/op/regs/regs.cc
dense = _APIS.get("mnm.op.imp.dense", None)
# Defined in ./src/op/regs/regs.cc
device_copy = _APIS.get("mnm.op.imp.device_copy", None)
# Defined in ./src/op/regs/regs.cc
divide = _APIS.get("mnm.op.imp.divide", None)
# Defined in ./src/op/regs/regs.cc
equal = _APIS.get("mnm.op.imp.equal", None)
# Defined in ./src/op/regs/regs.cc
erf = _APIS.get("mnm.op.imp.erf", None)
# Defined in ./src/op/regs/regs.cc
erf_dx = _APIS.get("mnm.op.imp.erf_dx", None)
# Defined in ./src/op/regs/regs.cc
exp = _APIS.get("mnm.op.imp.exp", None)
# Defined in ./src/op/regs/regs.cc
expand_dims = _APIS.get("mnm.op.imp.expand_dims", None)
# Defined in ./src/op/regs/regs.cc
floor = _APIS.get("mnm.op.imp.floor", None)
# Defined in ./src/op/regs/regs.cc
floor_divide = _APIS.get("mnm.op.imp.floor_divide", None)
# Defined in ./src/op/regs/regs.cc
full = _APIS.get("mnm.op.imp.full", None)
# Defined in ./src/op/regs/regs.cc
full_like = _APIS.get("mnm.op.imp.full_like", None)
# Defined in ./src/op/regs/regs.cc
gather = _APIS.get("mnm.op.imp.gather", None)
# Defined in ./src/op/regs/regs.cc
gather_dx = _APIS.get("mnm.op.imp.gather_dx", None)
# Defined in ./src/op/regs/regs.cc
gather_nd = _APIS.get("mnm.op.imp.gather_nd", None)
# Defined in ./src/op/regs/regs.cc
gather_nd_dx = _APIS.get("mnm.op.imp.gather_nd_dx", None)
# Defined in ./src/op/regs/regs.cc
gelu = _APIS.get("mnm.op.imp.gelu", None)
# Defined in ./src/op/regs/regs.cc
gelu_dx = _APIS.get("mnm.op.imp.gelu_dx", None)
# Defined in ./src/op/regs/regs.cc
get_kept_dims = _APIS.get("mnm.op.imp.get_kept_dims", None)
# Defined in ./src/op/regs/regs.cc
get_reduce_axis = _APIS.get("mnm.op.imp.get_reduce_axis", None)
# Defined in ./src/op/regs/regs.cc
get_valid_counts = _APIS.get("mnm.op.imp.get_valid_counts", None)
# Defined in ./src/op/regs/regs.cc
greater = _APIS.get("mnm.op.imp.greater", None)
# Defined in ./src/op/regs/regs.cc
greater_equal = _APIS.get("mnm.op.imp.greater_equal", None)
# Defined in ./src/op/regs/regs.cc
layer_norm = _APIS.get("mnm.op.imp.layer_norm", None)
# Defined in ./src/op/regs/regs.cc
layer_norm_dx = _APIS.get("mnm.op.imp.layer_norm_dx", None)
# Defined in ./src/op/regs/regs.cc
left_shift = _APIS.get("mnm.op.imp.left_shift", None)
# Defined in ./src/op/regs/regs.cc
less = _APIS.get("mnm.op.imp.less", None)
# Defined in ./src/op/regs/regs.cc
less_equal = _APIS.get("mnm.op.imp.less_equal", None)
# Defined in ./src/op/regs/regs.cc
log = _APIS.get("mnm.op.imp.log", None)
# Defined in ./src/op/regs/regs.cc
log2 = _APIS.get("mnm.op.imp.log2", None)
# Defined in ./src/op/regs/regs.cc
log_softmax = _APIS.get("mnm.op.imp.log_softmax", None)
# Defined in ./src/op/regs/regs.cc
log_softmax_dx = _APIS.get("mnm.op.imp.log_softmax_dx", None)
# Defined in ./src/op/regs/regs.cc
logical_and = _APIS.get("mnm.op.imp.logical_and", None)
# Defined in ./src/op/regs/regs.cc
logical_not = _APIS.get("mnm.op.imp.logical_not", None)
# Defined in ./src/op/regs/regs.cc
matmul = _APIS.get("mnm.op.imp.matmul", None)
# Defined in ./src/op/regs/regs.cc
matmul_nt = _APIS.get("mnm.op.imp.matmul_nt", None)
# Defined in ./src/op/regs/regs.cc
matmul_tn = _APIS.get("mnm.op.imp.matmul_tn", None)
# Defined in ./src/op/regs/regs.cc
matmul_tt = _APIS.get("mnm.op.imp.matmul_tt", None)
# Defined in ./src/op/regs/regs.cc
max = _APIS.get("mnm.op.imp.max", None)
# Defined in ./src/op/regs/regs.cc
max_pool2d = _APIS.get("mnm.op.imp.max_pool2d", None)
# Defined in ./src/op/regs/regs.cc
max_pool2d_dx = _APIS.get("mnm.op.imp.max_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
maximum = _APIS.get("mnm.op.imp.maximum", None)
# Defined in ./src/op/regs/regs.cc
mean = _APIS.get("mnm.op.imp.mean", None)
# Defined in ./src/op/regs/regs.cc
mean_dx = _APIS.get("mnm.op.imp.mean_dx", None)
# Defined in ./src/op/regs/regs.cc
mesh_grid = _APIS.get("mnm.op.imp.mesh_grid", None)
# Defined in ./src/op/regs/regs.cc
min = _APIS.get("mnm.op.imp.min", None)
# Defined in ./src/op/regs/regs.cc
minimum = _APIS.get("mnm.op.imp.minimum", None)
# Defined in ./src/op/regs/regs.cc
mod = _APIS.get("mnm.op.imp.mod", None)
# Defined in ./src/op/regs/regs.cc
multiply = _APIS.get("mnm.op.imp.multiply", None)
# Defined in ./src/op/regs/regs.cc
ndarray_size = _APIS.get("mnm.op.imp.ndarray_size", None)
# Defined in ./src/op/regs/regs.cc
negative = _APIS.get("mnm.op.imp.negative", None)
# Defined in ./src/op/regs/regs.cc
nll_loss = _APIS.get("mnm.op.imp.nll_loss", None)
# Defined in ./src/op/regs/regs.cc
nll_loss_dpred = _APIS.get("mnm.op.imp.nll_loss_dpred", None)
# Defined in ./src/op/regs/regs.cc
nll_loss_dtrue = _APIS.get("mnm.op.imp.nll_loss_dtrue", None)
# Defined in ./src/op/regs/regs.cc
non_max_suppression = _APIS.get("mnm.op.imp.non_max_suppression", None)
# Defined in ./src/op/regs/regs.cc
not_equal = _APIS.get("mnm.op.imp.not_equal", None)
# Defined in ./src/op/regs/regs.cc
one_hot = _APIS.get("mnm.op.imp.one_hot", None)
# Defined in ./src/op/regs/regs.cc
ones = _APIS.get("mnm.op.imp.ones", None)
# Defined in ./src/op/regs/regs.cc
ones_like = _APIS.get("mnm.op.imp.ones_like", None)
# Defined in ./src/op/regs/regs.cc
pad = _APIS.get("mnm.op.imp.pad", None)
# Defined in ./src/op/regs/regs.cc
power = _APIS.get("mnm.op.imp.power", None)
# Defined in ./src/op/regs/regs.cc
prod = _APIS.get("mnm.op.imp.prod", None)
# Defined in ./src/op/regs/regs.cc
prod_dx = _APIS.get("mnm.op.imp.prod_dx", None)
# Defined in ./src/op/regs/regs.cc
relu = _APIS.get("mnm.op.imp.relu", None)
# Defined in ./src/op/regs/regs.cc
relu_dx = _APIS.get("mnm.op.imp.relu_dx", None)
# Defined in ./src/op/regs/regs.cc
repeat = _APIS.get("mnm.op.imp.repeat", None)
# Defined in ./src/op/regs/regs.cc
repeat_dx = _APIS.get("mnm.op.imp.repeat_dx", None)
# Defined in ./src/op/regs/regs.cc
reshape = _APIS.get("mnm.op.imp.reshape", None)
# Defined in ./src/op/regs/regs.cc
resize = _APIS.get("mnm.op.imp.resize", None)
# Defined in ./src/op/regs/regs.cc
reverse = _APIS.get("mnm.op.imp.reverse", None)
# Defined in ./src/op/regs/regs.cc
reverse_sequence = _APIS.get("mnm.op.imp.reverse_sequence", None)
# Defined in ./src/op/regs/regs.cc
right_shift = _APIS.get("mnm.op.imp.right_shift", None)
# Defined in ./src/op/regs/regs.cc
roi_align = _APIS.get("mnm.op.imp.roi_align", None)
# Defined in ./src/op/regs/regs.cc
roi_align_dx = _APIS.get("mnm.op.imp.roi_align_dx", None)
# Defined in ./src/op/regs/regs.cc
round = _APIS.get("mnm.op.imp.round", None)
# Defined in ./src/op/regs/regs.cc
rsqrt = _APIS.get("mnm.op.imp.rsqrt", None)
# Defined in ./src/op/regs/regs.cc
scatter = _APIS.get("mnm.op.imp.scatter", None)
# Defined in ./src/op/regs/regs.cc
scatter_dx = _APIS.get("mnm.op.imp.scatter_dx", None)
# Defined in ./src/op/regs/regs.cc
sequence_mask = _APIS.get("mnm.op.imp.sequence_mask", None)
# Defined in ./src/op/regs/regs.cc
sgd = _APIS.get("mnm.op.imp.sgd", None)
# Defined in ./src/op/regs/regs.cc
shape = _APIS.get("mnm.op.imp.shape", None)
# Defined in ./src/op/regs/regs.cc
sigmoid = _APIS.get("mnm.op.imp.sigmoid", None)
# Defined in ./src/op/regs/regs.cc
sigmoid_dx = _APIS.get("mnm.op.imp.sigmoid_dx", None)
# Defined in ./src/op/regs/regs.cc
sign = _APIS.get("mnm.op.imp.sign", None)
# Defined in ./src/op/regs/regs.cc
sin = _APIS.get("mnm.op.imp.sin", None)
# Defined in ./src/op/regs/regs.cc
smooth_l1_loss = _APIS.get("mnm.op.imp.smooth_l1_loss", None)
# Defined in ./src/op/regs/regs.cc
smooth_l1_loss_dpred = _APIS.get("mnm.op.imp.smooth_l1_loss_dpred", None)
# Defined in ./src/op/regs/regs.cc
smooth_l1_loss_dtrue = _APIS.get("mnm.op.imp.smooth_l1_loss_dtrue", None)
# Defined in ./src/op/regs/regs.cc
softmax = _APIS.get("mnm.op.imp.softmax", None)
# Defined in ./src/op/regs/regs.cc
softmax_dx = _APIS.get("mnm.op.imp.softmax_dx", None)
# Defined in ./src/op/regs/regs.cc
sort = _APIS.get("mnm.op.imp.sort", None)
# Defined in ./src/op/regs/regs.cc
split = _APIS.get("mnm.op.imp.split", None)
# Defined in ./src/op/regs/regs.cc
sqrt = _APIS.get("mnm.op.imp.sqrt", None)
# Defined in ./src/op/regs/regs.cc
sqrt_dx = _APIS.get("mnm.op.imp.sqrt_dx", None)
# Defined in ./src/op/regs/regs.cc
squeeze = _APIS.get("mnm.op.imp.squeeze", None)
# Defined in ./src/op/regs/regs.cc
stack = _APIS.get("mnm.op.imp.stack", None)
# Defined in ./src/op/regs/regs.cc
stream_sync = _APIS.get("mnm.op.imp.stream_sync", None)
# Defined in ./src/op/regs/regs.cc
strided_slice = _APIS.get("mnm.op.imp.strided_slice", None)
# Defined in ./src/op/regs/regs.cc
strided_slice_dx = _APIS.get("mnm.op.imp.strided_slice_dx", None)
# Defined in ./src/op/regs/regs.cc
subtract = _APIS.get("mnm.op.imp.subtract", None)
# Defined in ./src/op/regs/regs.cc
sum = _APIS.get("mnm.op.imp.sum", None)
# Defined in ./src/op/regs/regs.cc
sum_dx = _APIS.get("mnm.op.imp.sum_dx", None)
# Defined in ./src/op/regs/regs.cc
swap_axis = _APIS.get("mnm.op.imp.swap_axis", None)
# Defined in ./src/op/regs/regs.cc
take = _APIS.get("mnm.op.imp.take", None)
# Defined in ./src/op/regs/regs.cc
take_dx = _APIS.get("mnm.op.imp.take_dx", None)
# Defined in ./src/op/regs/regs.cc
tanh = _APIS.get("mnm.op.imp.tanh", None)
# Defined in ./src/op/regs/regs.cc
tanh_dx = _APIS.get("mnm.op.imp.tanh_dx", None)
# Defined in ./src/op/regs/regs.cc
threefry_generate = _APIS.get("mnm.op.imp.threefry_generate", None)
# Defined in ./src/op/regs/regs.cc
threefry_split = _APIS.get("mnm.op.imp.threefry_split", None)
# Defined in ./src/op/regs/regs.cc
transpose = _APIS.get("mnm.op.imp.transpose", None)
# Defined in ./src/op/regs/regs.cc
transpose_dx = _APIS.get("mnm.op.imp.transpose_dx", None)
# Defined in ./src/op/regs/regs.cc
trunc = _APIS.get("mnm.op.imp.trunc", None)
# Defined in ./src/op/regs/regs.cc
where = _APIS.get("mnm.op.imp.where", None)
# Defined in ./src/op/regs/regs.cc
zeros = _APIS.get("mnm.op.imp.zeros", None)
# Defined in ./src/op/regs/regs.cc
zeros_like = _APIS.get("mnm.op.imp.zeros_like", None)
