# pylint: disable=invalid-name,redefined-builtin,line-too-long
# pylint: disable=missing-class-docstring,missing-function-docstring
"""Auto generated. Do not touch."""
from mnm._lib import _APIS
# Defined in ./src/op/regs/regs.cc
_allgather = _APIS.get("mnm.op.sym._allgather", None)
# Defined in ./src/op/regs/regs.cc
_allreduce = _APIS.get("mnm.op.sym._allreduce", None)
# Defined in ./src/op/regs/regs.cc
_broadcast = _APIS.get("mnm.op.sym._broadcast", None)
# Defined in ./src/op/regs/regs.cc
_contrib_dropout = _APIS.get("mnm.op.sym._contrib_dropout", None)
# Defined in ./src/op/regs/regs.cc
_contrib_dropout_dx = _APIS.get("mnm.op.sym._contrib_dropout_dx", None)
# Defined in ./src/op/regs/regs.cc
_recv = _APIS.get("mnm.op.sym._recv", None)
# Defined in ./src/op/regs/regs.cc
_reduce = _APIS.get("mnm.op.sym._reduce", None)
# Defined in ./src/op/regs/regs.cc
_reduce_scatter = _APIS.get("mnm.op.sym._reduce_scatter", None)
# Defined in ./src/op/regs/regs.cc
_send = _APIS.get("mnm.op.sym._send", None)
# Defined in ./src/op/regs/regs.cc
abs = _APIS.get("mnm.op.sym.abs", None)
# Defined in ./src/op/regs/regs.cc
adaptive_avg_pool2d = _APIS.get("mnm.op.sym.adaptive_avg_pool2d", None)
# Defined in ./src/op/regs/regs.cc
adaptive_avg_pool2d_dx = _APIS.get("mnm.op.sym.adaptive_avg_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
adaptive_max_pool2d = _APIS.get("mnm.op.sym.adaptive_max_pool2d", None)
# Defined in ./src/op/regs/regs.cc
adaptive_max_pool2d_dx = _APIS.get("mnm.op.sym.adaptive_max_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
add = _APIS.get("mnm.op.sym.add", None)
# Defined in ./src/op/regs/regs.cc
add_event = _APIS.get("mnm.op.sym.add_event", None)
# Defined in ./src/op/regs/regs.cc
adv_index = _APIS.get("mnm.op.sym.adv_index", None)
# Defined in ./src/op/regs/regs.cc
adv_index_dx = _APIS.get("mnm.op.sym.adv_index_dx", None)
# Defined in ./src/op/regs/regs.cc
all = _APIS.get("mnm.op.sym.all", None)
# Defined in ./src/op/regs/regs.cc
any = _APIS.get("mnm.op.sym.any", None)
# Defined in ./src/op/regs/regs.cc
arange = _APIS.get("mnm.op.sym.arange", None)
# Defined in ./src/op/regs/regs.cc
argmax = _APIS.get("mnm.op.sym.argmax", None)
# Defined in ./src/op/regs/regs.cc
argmin = _APIS.get("mnm.op.sym.argmin", None)
# Defined in ./src/op/regs/regs.cc
argsort = _APIS.get("mnm.op.sym.argsort", None)
# Defined in ./src/op/regs/regs.cc
argwhere = _APIS.get("mnm.op.sym.argwhere", None)
# Defined in ./src/op/regs/regs.cc
atan = _APIS.get("mnm.op.sym.atan", None)
# Defined in ./src/op/regs/regs.cc
avg_pool2d = _APIS.get("mnm.op.sym.avg_pool2d", None)
# Defined in ./src/op/regs/regs.cc
avg_pool2d_dx = _APIS.get("mnm.op.sym.avg_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
batch_flatten = _APIS.get("mnm.op.sym.batch_flatten", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul = _APIS.get("mnm.op.sym.batch_matmul", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul_nt = _APIS.get("mnm.op.sym.batch_matmul_nt", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul_tn = _APIS.get("mnm.op.sym.batch_matmul_tn", None)
# Defined in ./src/op/regs/regs.cc
batch_matmul_tt = _APIS.get("mnm.op.sym.batch_matmul_tt", None)
# Defined in ./src/op/regs/regs.cc
batch_norm_infer = _APIS.get("mnm.op.sym.batch_norm_infer", None)
# Defined in ./src/op/regs/regs.cc
batch_norm_train = _APIS.get("mnm.op.sym.batch_norm_train", None)
# Defined in ./src/op/regs/regs.cc
batch_norm_train_dxwb = _APIS.get("mnm.op.sym.batch_norm_train_dxwb", None)
# Defined in ./src/op/regs/regs.cc
bias_add = _APIS.get("mnm.op.sym.bias_add", None)
# Defined in ./src/op/regs/regs.cc
broadcast_to = _APIS.get("mnm.op.sym.broadcast_to", None)
# Defined in ./src/op/regs/regs.cc
broadcast_to_like = _APIS.get("mnm.op.sym.broadcast_to_like", None)
# Defined in ./src/op/regs/regs.cc
cast = _APIS.get("mnm.op.sym.cast", None)
# Defined in ./src/op/regs/regs.cc
cast_like = _APIS.get("mnm.op.sym.cast_like", None)
# Defined in ./src/op/regs/regs.cc
ceil = _APIS.get("mnm.op.sym.ceil", None)
# Defined in ./src/op/regs/regs.cc
clip = _APIS.get("mnm.op.sym.clip", None)
# Defined in ./src/op/regs/regs.cc
clip_dx = _APIS.get("mnm.op.sym.clip_dx", None)
# Defined in ./src/op/regs/regs.cc
collapse_sum_like = _APIS.get("mnm.op.sym.collapse_sum_like", None)
# Defined in ./src/op/regs/regs.cc
compiler_begin = _APIS.get("mnm.op.sym.compiler_begin", None)
# Defined in ./src/op/regs/regs.cc
compiler_end = _APIS.get("mnm.op.sym.compiler_end", None)
# Defined in ./src/op/regs/regs.cc
concatenate = _APIS.get("mnm.op.sym.concatenate", None)
# Defined in ./src/op/regs/regs.cc
concatenate_dx = _APIS.get("mnm.op.sym.concatenate_dx", None)
# Defined in ./src/op/regs/regs.cc
conv2d = _APIS.get("mnm.op.sym.conv2d", None)
# Defined in ./src/op/regs/regs.cc
conv2d_dw = _APIS.get("mnm.op.sym.conv2d_dw", None)
# Defined in ./src/op/regs/regs.cc
conv2d_dx = _APIS.get("mnm.op.sym.conv2d_dx", None)
# Defined in ./src/op/regs/regs.cc
conv2d_transpose = _APIS.get("mnm.op.sym.conv2d_transpose", None)
# Defined in ./src/op/regs/regs.cc
conv2d_transpose_dw = _APIS.get("mnm.op.sym.conv2d_transpose_dw", None)
# Defined in ./src/op/regs/regs.cc
conv2d_transpose_dx = _APIS.get("mnm.op.sym.conv2d_transpose_dx", None)
# Defined in ./src/op/regs/regs.cc
copy = _APIS.get("mnm.op.sym.copy", None)
# Defined in ./src/op/regs/regs.cc
cos = _APIS.get("mnm.op.sym.cos", None)
# Defined in ./src/op/regs/regs.cc
cross_entropy = _APIS.get("mnm.op.sym.cross_entropy", None)
# Defined in ./src/op/regs/regs.cc
cross_entropy_dpred = _APIS.get("mnm.op.sym.cross_entropy_dpred", None)
# Defined in ./src/op/regs/regs.cc
cross_entropy_dtrue = _APIS.get("mnm.op.sym.cross_entropy_dtrue", None)
# Defined in ./src/op/regs/regs.cc
cumsum = _APIS.get("mnm.op.sym.cumsum", None)
# Defined in ./src/op/regs/regs.cc
dense = _APIS.get("mnm.op.sym.dense", None)
# Defined in ./src/op/regs/regs.cc
device_copy = _APIS.get("mnm.op.sym.device_copy", None)
# Defined in ./src/op/regs/regs.cc
divide = _APIS.get("mnm.op.sym.divide", None)
# Defined in ./src/op/regs/regs.cc
embedding = _APIS.get("mnm.op.sym.embedding", None)
# Defined in ./src/op/regs/regs.cc
embedding_dx = _APIS.get("mnm.op.sym.embedding_dx", None)
# Defined in ./src/op/regs/regs.cc
equal = _APIS.get("mnm.op.sym.equal", None)
# Defined in ./src/op/regs/regs.cc
erf = _APIS.get("mnm.op.sym.erf", None)
# Defined in ./src/op/regs/regs.cc
erf_dx = _APIS.get("mnm.op.sym.erf_dx", None)
# Defined in ./src/op/regs/regs.cc
exp = _APIS.get("mnm.op.sym.exp", None)
# Defined in ./src/op/regs/regs.cc
expand_dims = _APIS.get("mnm.op.sym.expand_dims", None)
# Defined in ./src/op/regs/regs.cc
floor = _APIS.get("mnm.op.sym.floor", None)
# Defined in ./src/op/regs/regs.cc
floor_divide = _APIS.get("mnm.op.sym.floor_divide", None)
# Defined in ./src/op/regs/regs.cc
full = _APIS.get("mnm.op.sym.full", None)
# Defined in ./src/op/regs/regs.cc
full_like = _APIS.get("mnm.op.sym.full_like", None)
# Defined in ./src/op/regs/regs.cc
gather = _APIS.get("mnm.op.sym.gather", None)
# Defined in ./src/op/regs/regs.cc
gather_dx = _APIS.get("mnm.op.sym.gather_dx", None)
# Defined in ./src/op/regs/regs.cc
gather_nd = _APIS.get("mnm.op.sym.gather_nd", None)
# Defined in ./src/op/regs/regs.cc
gather_nd_dx = _APIS.get("mnm.op.sym.gather_nd_dx", None)
# Defined in ./src/op/regs/regs.cc
gelu = _APIS.get("mnm.op.sym.gelu", None)
# Defined in ./src/op/regs/regs.cc
gelu_dx = _APIS.get("mnm.op.sym.gelu_dx", None)
# Defined in ./src/op/regs/regs.cc
get_kept_dims = _APIS.get("mnm.op.sym.get_kept_dims", None)
# Defined in ./src/op/regs/regs.cc
get_reduce_axis = _APIS.get("mnm.op.sym.get_reduce_axis", None)
# Defined in ./src/op/regs/regs.cc
get_valid_counts = _APIS.get("mnm.op.sym.get_valid_counts", None)
# Defined in ./src/op/regs/regs.cc
greater = _APIS.get("mnm.op.sym.greater", None)
# Defined in ./src/op/regs/regs.cc
greater_equal = _APIS.get("mnm.op.sym.greater_equal", None)
# Defined in ./src/op/regs/regs.cc
l2norm = _APIS.get("mnm.op.sym.l2norm", None)
# Defined in ./src/op/regs/regs.cc
layer_norm = _APIS.get("mnm.op.sym.layer_norm", None)
# Defined in ./src/op/regs/regs.cc
layer_norm_dx = _APIS.get("mnm.op.sym.layer_norm_dx", None)
# Defined in ./src/op/regs/regs.cc
left_shift = _APIS.get("mnm.op.sym.left_shift", None)
# Defined in ./src/op/regs/regs.cc
less = _APIS.get("mnm.op.sym.less", None)
# Defined in ./src/op/regs/regs.cc
less_equal = _APIS.get("mnm.op.sym.less_equal", None)
# Defined in ./src/op/regs/regs.cc
log = _APIS.get("mnm.op.sym.log", None)
# Defined in ./src/op/regs/regs.cc
log2 = _APIS.get("mnm.op.sym.log2", None)
# Defined in ./src/op/regs/regs.cc
log_softmax = _APIS.get("mnm.op.sym.log_softmax", None)
# Defined in ./src/op/regs/regs.cc
log_softmax_dx = _APIS.get("mnm.op.sym.log_softmax_dx", None)
# Defined in ./src/op/regs/regs.cc
logical_and = _APIS.get("mnm.op.sym.logical_and", None)
# Defined in ./src/op/regs/regs.cc
logical_not = _APIS.get("mnm.op.sym.logical_not", None)
# Defined in ./src/op/regs/regs.cc
matmul = _APIS.get("mnm.op.sym.matmul", None)
# Defined in ./src/op/regs/regs.cc
matmul_nt = _APIS.get("mnm.op.sym.matmul_nt", None)
# Defined in ./src/op/regs/regs.cc
matmul_tn = _APIS.get("mnm.op.sym.matmul_tn", None)
# Defined in ./src/op/regs/regs.cc
matmul_tt = _APIS.get("mnm.op.sym.matmul_tt", None)
# Defined in ./src/op/regs/regs.cc
max = _APIS.get("mnm.op.sym.max", None)
# Defined in ./src/op/regs/regs.cc
max_pool2d = _APIS.get("mnm.op.sym.max_pool2d", None)
# Defined in ./src/op/regs/regs.cc
max_pool2d_dx = _APIS.get("mnm.op.sym.max_pool2d_dx", None)
# Defined in ./src/op/regs/regs.cc
maximum = _APIS.get("mnm.op.sym.maximum", None)
# Defined in ./src/op/regs/regs.cc
mean = _APIS.get("mnm.op.sym.mean", None)
# Defined in ./src/op/regs/regs.cc
mean_dx = _APIS.get("mnm.op.sym.mean_dx", None)
# Defined in ./src/op/regs/regs.cc
mesh_grid = _APIS.get("mnm.op.sym.mesh_grid", None)
# Defined in ./src/op/regs/regs.cc
min = _APIS.get("mnm.op.sym.min", None)
# Defined in ./src/op/regs/regs.cc
minimum = _APIS.get("mnm.op.sym.minimum", None)
# Defined in ./src/op/regs/regs.cc
mod = _APIS.get("mnm.op.sym.mod", None)
# Defined in ./src/op/regs/regs.cc
multiply = _APIS.get("mnm.op.sym.multiply", None)
# Defined in ./src/op/regs/regs.cc
ndarray_size = _APIS.get("mnm.op.sym.ndarray_size", None)
# Defined in ./src/op/regs/regs.cc
negative = _APIS.get("mnm.op.sym.negative", None)
# Defined in ./src/op/regs/regs.cc
nll_loss = _APIS.get("mnm.op.sym.nll_loss", None)
# Defined in ./src/op/regs/regs.cc
nll_loss_dpred = _APIS.get("mnm.op.sym.nll_loss_dpred", None)
# Defined in ./src/op/regs/regs.cc
nll_loss_dtrue = _APIS.get("mnm.op.sym.nll_loss_dtrue", None)
# Defined in ./src/op/regs/regs.cc
non_max_suppression = _APIS.get("mnm.op.sym.non_max_suppression", None)
# Defined in ./src/op/regs/regs.cc
not_equal = _APIS.get("mnm.op.sym.not_equal", None)
# Defined in ./src/op/regs/regs.cc
numel = _APIS.get("mnm.op.sym.numel", None)
# Defined in ./src/op/regs/regs.cc
one_hot = _APIS.get("mnm.op.sym.one_hot", None)
# Defined in ./src/op/regs/regs.cc
ones = _APIS.get("mnm.op.sym.ones", None)
# Defined in ./src/op/regs/regs.cc
ones_like = _APIS.get("mnm.op.sym.ones_like", None)
# Defined in ./src/op/regs/regs.cc
pad = _APIS.get("mnm.op.sym.pad", None)
# Defined in ./src/op/regs/regs.cc
power = _APIS.get("mnm.op.sym.power", None)
# Defined in ./src/op/regs/regs.cc
prod = _APIS.get("mnm.op.sym.prod", None)
# Defined in ./src/op/regs/regs.cc
prod_dx = _APIS.get("mnm.op.sym.prod_dx", None)
# Defined in ./src/op/regs/regs.cc
relu = _APIS.get("mnm.op.sym.relu", None)
# Defined in ./src/op/regs/regs.cc
relu_dx = _APIS.get("mnm.op.sym.relu_dx", None)
# Defined in ./src/op/regs/regs.cc
repeat = _APIS.get("mnm.op.sym.repeat", None)
# Defined in ./src/op/regs/regs.cc
repeat_dx = _APIS.get("mnm.op.sym.repeat_dx", None)
# Defined in ./src/op/regs/regs.cc
reshape = _APIS.get("mnm.op.sym.reshape", None)
# Defined in ./src/op/regs/regs.cc
resize2d = _APIS.get("mnm.op.sym.resize2d", None)
# Defined in ./src/op/regs/regs.cc
resize2d_dx = _APIS.get("mnm.op.sym.resize2d_dx", None)
# Defined in ./src/op/regs/regs.cc
reverse = _APIS.get("mnm.op.sym.reverse", None)
# Defined in ./src/op/regs/regs.cc
reverse_sequence = _APIS.get("mnm.op.sym.reverse_sequence", None)
# Defined in ./src/op/regs/regs.cc
right_shift = _APIS.get("mnm.op.sym.right_shift", None)
# Defined in ./src/op/regs/regs.cc
roi_align = _APIS.get("mnm.op.sym.roi_align", None)
# Defined in ./src/op/regs/regs.cc
roi_align_dx = _APIS.get("mnm.op.sym.roi_align_dx", None)
# Defined in ./src/op/regs/regs.cc
round = _APIS.get("mnm.op.sym.round", None)
# Defined in ./src/op/regs/regs.cc
rsqrt = _APIS.get("mnm.op.sym.rsqrt", None)
# Defined in ./src/op/regs/regs.cc
scatter = _APIS.get("mnm.op.sym.scatter", None)
# Defined in ./src/op/regs/regs.cc
scatter_dx = _APIS.get("mnm.op.sym.scatter_dx", None)
# Defined in ./src/op/regs/regs.cc
sequence_mask = _APIS.get("mnm.op.sym.sequence_mask", None)
# Defined in ./src/op/regs/regs.cc
set_stream = _APIS.get("mnm.op.sym.set_stream", None)
# Defined in ./src/op/regs/regs.cc
sgd = _APIS.get("mnm.op.sym.sgd", None)
# Defined in ./src/op/regs/regs.cc
shape = _APIS.get("mnm.op.sym.shape", None)
# Defined in ./src/op/regs/regs.cc
shape_as_tensor = _APIS.get("mnm.op.sym.shape_as_tensor", None)
# Defined in ./src/op/regs/regs.cc
sigmoid = _APIS.get("mnm.op.sym.sigmoid", None)
# Defined in ./src/op/regs/regs.cc
sigmoid_dx = _APIS.get("mnm.op.sym.sigmoid_dx", None)
# Defined in ./src/op/regs/regs.cc
sign = _APIS.get("mnm.op.sym.sign", None)
# Defined in ./src/op/regs/regs.cc
sin = _APIS.get("mnm.op.sym.sin", None)
# Defined in ./src/op/regs/regs.cc
size = _APIS.get("mnm.op.sym.size", None)
# Defined in ./src/op/regs/regs.cc
smooth_l1_loss = _APIS.get("mnm.op.sym.smooth_l1_loss", None)
# Defined in ./src/op/regs/regs.cc
smooth_l1_loss_dpred = _APIS.get("mnm.op.sym.smooth_l1_loss_dpred", None)
# Defined in ./src/op/regs/regs.cc
smooth_l1_loss_dtrue = _APIS.get("mnm.op.sym.smooth_l1_loss_dtrue", None)
# Defined in ./src/op/regs/regs.cc
softmax = _APIS.get("mnm.op.sym.softmax", None)
# Defined in ./src/op/regs/regs.cc
softmax_dx = _APIS.get("mnm.op.sym.softmax_dx", None)
# Defined in ./src/op/regs/regs.cc
sort = _APIS.get("mnm.op.sym.sort", None)
# Defined in ./src/op/regs/regs.cc
split = _APIS.get("mnm.op.sym.split", None)
# Defined in ./src/op/regs/regs.cc
sqrt = _APIS.get("mnm.op.sym.sqrt", None)
# Defined in ./src/op/regs/regs.cc
sqrt_dx = _APIS.get("mnm.op.sym.sqrt_dx", None)
# Defined in ./src/op/regs/regs.cc
squeeze = _APIS.get("mnm.op.sym.squeeze", None)
# Defined in ./src/op/regs/regs.cc
stack = _APIS.get("mnm.op.sym.stack", None)
# Defined in ./src/op/regs/regs.cc
stream_barrier = _APIS.get("mnm.op.sym.stream_barrier", None)
# Defined in ./src/op/regs/regs.cc
stream_sync = _APIS.get("mnm.op.sym.stream_sync", None)
# Defined in ./src/op/regs/regs.cc
strided_slice = _APIS.get("mnm.op.sym.strided_slice", None)
# Defined in ./src/op/regs/regs.cc
strided_slice_dx = _APIS.get("mnm.op.sym.strided_slice_dx", None)
# Defined in ./src/op/regs/regs.cc
subtract = _APIS.get("mnm.op.sym.subtract", None)
# Defined in ./src/op/regs/regs.cc
sum = _APIS.get("mnm.op.sym.sum", None)
# Defined in ./src/op/regs/regs.cc
sum_dx = _APIS.get("mnm.op.sym.sum_dx", None)
# Defined in ./src/op/regs/regs.cc
swap_axis = _APIS.get("mnm.op.sym.swap_axis", None)
# Defined in ./src/op/regs/regs.cc
take = _APIS.get("mnm.op.sym.take", None)
# Defined in ./src/op/regs/regs.cc
take_dx = _APIS.get("mnm.op.sym.take_dx", None)
# Defined in ./src/op/regs/regs.cc
tanh = _APIS.get("mnm.op.sym.tanh", None)
# Defined in ./src/op/regs/regs.cc
tanh_dx = _APIS.get("mnm.op.sym.tanh_dx", None)
# Defined in ./src/op/regs/regs.cc
threefry_generate = _APIS.get("mnm.op.sym.threefry_generate", None)
# Defined in ./src/op/regs/regs.cc
threefry_split = _APIS.get("mnm.op.sym.threefry_split", None)
# Defined in ./src/op/regs/regs.cc
threshold = _APIS.get("mnm.op.sym.threshold", None)
# Defined in ./src/op/regs/regs.cc
threshold_dx = _APIS.get("mnm.op.sym.threshold_dx", None)
# Defined in ./src/op/regs/regs.cc
topk = _APIS.get("mnm.op.sym.topk", None)
# Defined in ./src/op/regs/regs.cc
transpose = _APIS.get("mnm.op.sym.transpose", None)
# Defined in ./src/op/regs/regs.cc
transpose_dx = _APIS.get("mnm.op.sym.transpose_dx", None)
# Defined in ./src/op/regs/regs.cc
trunc = _APIS.get("mnm.op.sym.trunc", None)
# Defined in ./src/op/regs/regs.cc
wait_event = _APIS.get("mnm.op.sym.wait_event", None)
# Defined in ./src/op/regs/regs.cc
where = _APIS.get("mnm.op.sym.where", None)
# Defined in ./src/op/regs/regs.cc
zeros = _APIS.get("mnm.op.sym.zeros", None)
# Defined in ./src/op/regs/regs.cc
zeros_like = _APIS.get("mnm.op.sym.zeros_like", None)
