#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This script enables pre-commit lint check.
# Put it to .git/hook/pre-commit to enable it!

clang_format=`which clang-format`

if [ $? -eq "0" ]; then
  cached=`git diff --cached --name-only | grep "\.[c$|cc$|h$]"`
  for i in $cached; do
    clang-format $i -output-replacements-xml | grep "<replacement " > /dev/null
    if [ $? -ne "1" ]; then
      echo $i mismatch the result of clang-format.
      echo Please run scripts/lint/run-clang-format.sh to correct it!
      exit 1
    fi
  done
  echo Lint check pass! Commit the changes!
else
  echo "[Warning] You have not installed a clang-format"
  echo "          Pre-commit code format is skipped"
  echo "          It is recommended to have it installed"
fi
