ci_cpu = "junrushao1994/mnm:ci_cpu-v0.03"
ci_gpu = "junrushao1994/mnm:ci_gpu-v0.03"

docker_run = 'docker/bash.sh'
max_time = 120

mnm_multilib = "build/config.cmake, " +
               "build/lib/libtvm_topi.so, " +
               "build/lib/libtvm.so, " +
               "build/lib/libmnm.so"

def init_git_unix() {
  checkout scm
  retry(5) {
    timeout(time: 2, unit: 'MINUTES') {
      sh 'git submodule update --init --recursive'
    }
  }
}

def init_git_win() {
  checkout scm
  retry(5) {
    timeout(time: 2, unit: 'MINUTES') {
      bat 'git submodule update --init --recursive'
    }
  }
}

def make(docker_type, path) {
  timeout(time: max_time, unit: 'MINUTES') {
    try {
      sh "${docker_run} ${docker_type} ./ci/task_build.sh ${path} -j\$(nproc)"
      sh "${docker_run} ${docker_type} ./ci/task_cpp_unittest.sh"
    } catch (exc) {
      echo 'Incremental compilation failed. Fall back to build from scratch'
      sh "${docker_run} ${docker_type} ./ci/task_clean.sh ${path}" 
      sh "${docker_run} ${docker_type} ./ci/task_build.sh ${path} -j\$(nproc)"
      sh "${docker_run} ${docker_type} ./ci/task_cpp_unittest.sh"
    }
  }
}

def pack_lib(name, libs) {
  sh """
     echo "Packing ${libs} into ${name}"
     echo ${libs} | sed -e 's/,/ /g' | xargs md5sum
     """
  stash includes: libs, name: name
}

def unpack_lib(name, libs) {
  unstash name
  sh """
     echo "Unpacked ${libs} from ${name}"
     echo ${libs} | sed -e 's/,/ /g' | xargs md5sum
     """
}

stage("Lint") {
  timeout(time: max_time, unit: 'MINUTES') {
    node('linux-cpu') {
      init_git_unix()
      sh "${docker_run} ${ci_cpu} ./ci/task_lint.sh"
    }
  }
}

stage('Build') {
  parallel 'BUILD: GPU': {
    node('linux-gpu') {
      init_git_unix()
      sh """
         mkdir -p build
         cd build
         cp ../cmake/config.cmake .
         echo "set(MNM_USE_LLVM llvm-config-8)" >> config.cmake
         echo "set(MNM_USE_GTEST ON)" >> config.cmake
         echo "set(MNM_USE_CUDA ON)" >> config.cmake
         echo "set(MNM_USE_CUDNN ON)" >> config.cmake
         echo "set(CMAKE_BUILD_TYPE Release)" >> config.cmake
         """
      make(ci_gpu, 'build')
      pack_lib('gpu', mnm_multilib)
    }
  },
  'BUILD: CPU': {
    node('linux-cpu') {
      init_git_unix()
      sh """
         mkdir -p build
         cd build
         cp ../cmake/config.cmake .
         echo "set(MNM_USE_LLVM llvm-config-8)" >> config.cmake
         echo "set(MNM_USE_GTEST ON)" >> config.cmake
         echo "set(MNM_USE_CUDA OFF)" >> config.cmake
         echo "set(MNM_USE_CUDNN OFF)" >> config.cmake
         echo "set(CMAKE_BUILD_TYPE Release)" >> config.cmake
         """
      make(ci_cpu, 'build')
      pack_lib('cpu', mnm_multilib)
    }
  }
}

stage('Unit Test') {
  parallel 'python3: GPU': {
    node('linux-gpu') {
      init_git_unix()
      unpack_lib('gpu', mnm_multilib)
      timeout(time: max_time, unit: 'MINUTES') {
        sh "${docker_run} ${ci_gpu} ./ci/task_python_unittest.sh"
      }
    }
  },
  'python3: CPU': {
    node('linux-cpu') {
      init_git_unix()
      unpack_lib('cpu', mnm_multilib)
      timeout(time: max_time, unit: 'MINUTES') {
        sh "${docker_run} ${ci_cpu} ./ci/task_python_unittest.sh"
      }
    }
  }
}
