# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""The extended gemm operation. Origin: cutlass/tools/library/scripts/gemm_operation.py"""
import gemm_operation
from library import *
from library_ext import *


class GemmOperationExt(gemm_operation.GemmOperation):
    def core_name(self):
        inst_shape = ""
        inst_operation = ""
        intermediate_type = ""

        math_operations_map = {
            MathOperation.xor_popc: "xor",
        }

        if (
            self.tile_description.math_instruction.opcode_class == OpcodeClass.TensorOp
            or self.tile_description.math_instruction.opcode_class == OpcodeClass.WmmaTensorOp
        ):

            math_op = self.tile_description.math_instruction.math_operation
            math_op_string = (
                math_operations_map[math_op] if math_op in math_operations_map.keys() else ""
            )

            inst_shape = "%d%d%d" % tuple(self.tile_description.math_instruction.instruction_shape)
            inst_shape += math_op_string

            if (
                self.tile_description.math_instruction.element_a != self.A.element
                and self.tile_description.math_instruction.element_a
                != self.tile_description.math_instruction.element_accumulator
            ):
                intermediate_type = DataTypeNames[self.tile_description.math_instruction.element_a]

        return "%s%s%s%s%s" % (
            self.short_math_name(),
            inst_shape,
            intermediate_type,
            GemmKindNames[self.gemm_kind],
            EpilogueFunctorNames[self.epilogue_functor],
        )


class EmitGemmConfigurationLibraryExt(gemm_operation.EmitGemmConfigurationLibrary):
    def __init__(self, operation_path, configuration_name):
        super().__init__(operation_path, configuration_name)

        self.gemm_kind_wrappers = {
            GemmKind.Gemm: "GemmOperation",
            GemmKind.Sparse: "GemmSparseOperation",
            GemmKind.Universal: "GemmUniversalOperationExt",
            GemmKind.PlanarComplex: "GemmPlanarComplexOperation",
            GemmKind.PlanarComplexArray: "GemmPlanarComplexArrayOperation",
        }

        self.header_template = """
/*
  Generated by gemm_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////
#include "cutlass/arch/wmma.h"
#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"
#include "cutlass_ext/library/gemm_operation_ext.h"

#include "library_internal.h"
#include "gemm_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////

"""


def make_gemm_operation_ext(op):
    return GemmOperationExt(
        op.gemm_kind,
        op.arch,
        op.tile_description,
        op.A,
        op.B,
        op.C,
        op.element_epilogue,
        op.epilogue_functor,
        op.swizzling_functor,
    )
