# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: CI-Lint

on:
  push:
    branches:
      - main
  # Since we use pull_request which allows workflow to checkout PRs,
  # we cannot use AWS credential in this workflow. Instead, we trigger
  # another workflow to run the rest CI jobs on AWS batch.
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  lint:
    if: github.repository == 'awslabs/raf'
    runs-on: ubuntu-latest
    container:
        image: metaprojdev/raf:ci_cpu-v0.19
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout all branches and history.
          submodules: 'recursive'
      - name: Check linting
        run: bash ./ci/task_lint.sh
      - name: Check src_codegen
        run: bash ./ci/task_check_autogen.sh
      - name: Check whether to skip rest tests
        # If the PR only changes docs or docker file, no need to run other tests.
        id: check_skip
        continue-on-error: true
        run: |
          bash ./scripts/lint/git-skip-testing.sh
          SKIP_CI=$(bash ./scripts/lint/git-skip-testing.sh)
          echo "skip_ci=${SKIP_CI}" >> $GITHUB_OUTPUT
      - name: Save common job info
        # Initialize the artifact and whether to skip CI.
        run: |
          mkdir job_info
          echo "Skip CI? ${{ steps.check_skip.outputs.skip_ci }}"
          echo "${{ steps.check_skip.outputs.skip_ci }}" > job_info/skip.txt
      - name: Save push event job info
        # Dump the job information for running CI with a new commit on main branch.
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_REF_ENV: ${{ github.ref }}
          GITHUB_REPO_ENV: ${{ github.repository }}
        run: |
          echo "Ref: \"$GITHUB_REF_ENV\""
          echo "Repo: \"$GITHUB_REPO_ENV\""
          echo "$GITHUB_REF_ENV" > job_info/ref.txt
          echo "$GITHUB_REPO_ENV" > job_info/repo.txt
      - name: Save pull request event job info
        # Dump the job information for running CI with a pull request.
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        env:
          REF_ENV: ${{ github.event.pull_request.head.ref }}
          REPO_ENV: ${{ github.event.pull_request.head.repo.full_name }}
          NUMBER_ENV: ${{ github.event.number }}
          SHA_ENV: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Ref: \"$REF_ENV\""
          echo "FullName: \"$REPO_ENV\""
          echo "Number: \"$NUMBER_ENV\""
          echo "HeadSHA: \"$SHA_ENV\""
          echo "$REF_ENV" > job_info/ref.txt
          echo "$REPO_ENV" > job_info/repo.txt
          echo "$NUMBER_ENV" > job_info/pr.txt
          echo "$SHA_ENV" > job_info/sha.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: job_info
          retention-days: 3
