# pylint: disable=invalid-name,redefined-builtin
# pylint: disable=missing-class-docstring,missing-function-docstring
"""Auto generated. Do not touch."""
from mnm._lib import _APIS
# Defined in ./src/pass/annotate_target.cc
AnnotateTarget = _APIS.get("mnm.pass_.AnnotateTarget", None)
# Defined in ./src/pass/assign_device.cc
AssignDevice = _APIS.get("mnm.pass_.AssignDevice", None)
# Defined in ./src/pass/auto_cast.cc
AutoCast = _APIS.get("mnm.pass_.AutoCast", None)
# Defined in ./src/pass/data_parallel.cc
AutoDataParallel = _APIS.get("mnm.pass_.AutoDataParallel", None)
# Defined in ./src/pass/gradient.cc
AutoDiff = _APIS.get("mnm.pass_.AutoDiff", None)
# Defined in ./src/pass/fold_const.cc
BindParam = _APIS.get("mnm.pass_.BindParam", None)
# Defined in ./src/pass/canonicalize_ops.cc
CanonicalizeOps = _APIS.get("mnm.pass_.CanonicalizeOps", None)
# Defined in ./src/pass/context_analysis.cc
ContextAnalysis = _APIS.get("mnm.pass_.ContextAnalysis", None)
# Defined in ./src/pass/dead_code.cc
DeadCodeElimination = _APIS.get("mnm.pass_.DeadCodeElimination", None)
# Defined in ./src/pass/substitute.cc
ExprAppend = _APIS.get("mnm.pass_.ExprAppend", None)
# Defined in ./src/pass/extract_binding.cc
ExtractBinding = _APIS.get("mnm.pass_.ExtractBinding", None)
# Defined in ./src/pass/fold_const.cc
FoldConstant = _APIS.get("mnm.pass_.FoldConstant", None)
# Defined in ./src/pass/from_relay.cc
FromRelay = _APIS.get("mnm.pass_.FromRelay", None)
# Defined in ./src/pass/fuse_ops.cc
FuseOps = _APIS.get("mnm.pass_.FuseOps", None)
# Defined in ./src/pass/grad_arg_select.cc
GradientInputSelection = _APIS.get("mnm.pass_.GradientInputSelection", None)
# Defined in ./src/pass/type_infer.cc
InferType = _APIS.get("mnm.pass_.InferType", None)
# Defined in ./src/pass/inline_backward.cc
InlineBackward = _APIS.get("mnm.pass_.InlineBackward", None)
# Defined in ./src/pass/inline_let.cc
InlineLet = _APIS.get("mnm.pass_.InlineLet", None)
# Defined in ./src/pass/inplace_update.cc
InplaceUpdate = _APIS.get("mnm.pass_.InplaceUpdate", None)
# Defined in ./src/pass/lambda_lift.cc
LambdaLift = _APIS.get("mnm.pass_.LambdaLift", None)
# Defined in ./src/pass/lift_branch_body.cc
LiftBranchBody = _APIS.get("mnm.pass_.LiftBranchBody", None)
# Defined in ./src/pass/manifest_alloc.cc
ManifestAlloc = _APIS.get("mnm.pass_.ManifestAlloc", None)
# Defined in ./src/pass/memory_share.cc
MemShare = _APIS.get("mnm.pass_.MemShare", None)
# Defined in ./src/pass/merge_compiler_regions.cc
MergeCompilerRegions = _APIS.get("mnm.pass_.MergeCompilerRegions", None)
# Defined in ./src/pass/partition_graph.cc
PartitionGraph = _APIS.get("mnm.pass_.PartitionGraph", None)
# Defined in ./src/pass/rename_vars.cc
RenameVars = _APIS.get("mnm.pass_.RenameVars", None)
# Defined in ./src/pass/simplify_expr.cc
SimplifyExpr = _APIS.get("mnm.pass_.SimplifyExpr", None)
# Defined in ./src/pass/substitute.cc
Substitute = _APIS.get("mnm.pass_.Substitute", None)
# Defined in ./src/pass/to_a_normal_form.cc
ToANormalForm = _APIS.get("mnm.pass_.ToANormalForm", None)
# Defined in ./src/pass/to_graph_normal_form.cc
ToGraphNormalForm = _APIS.get("mnm.pass_.ToGraphNormalForm", None)
# Defined in ./src/pass/fold_const.cc
is_constant = _APIS.get("mnm.pass_.is_constant", None)
# Defined in ./src/pass/from_relay.cc
validate_relay_param_name = _APIS.get("mnm.pass_.validate_relay_param_name", None)
